### ISSUE TITLE
Using same file/url results in having to reload entire document and reload chunks etc.

### ISSUE THREAD

**Issue by pohm-github** [bhaskatripathi/pdfGPT#1]
Use case is we want to ask multiple questions using the same file (i.e. the file is a faq and we have a number of different questions to ask about it (the questions are unrelated so this isn't a conversation just a plain question).

Using same file/url results in having to reload entire document and reload chunks etc. would be nice if the url or file are unchanged from the last submission that this process didn't need to occur since we already have generated the recommender previously.

**Comment by bhaskatripathi** [comment]
If I understand it correctly, you want to ask multiple questions to the same uploaded file or URL ?right? This is happening currently. Yo do not need to load the file again and keep asking as many questions as you want..

**Comment by pohm-github** [comment]
Yes your understanding is correct. My suggestion though is to optimise the
current process. Currently every time a question is asked the pdf file is
loaded, processed to text, chunks created and then embeddings. It would be
more efficient to simply call the previous embeddings created previously
instead of reprocessing the same file many times.

**Comment by pohm-github** [comment]
I'm other words the load_recommender function is called everytime the
function question_answer is called via the button event in the UI. It would
be far more efficient to only do this when the file has been changed.
Hopefully this makes sense.

**Comment by bhaskatripathi** [comment]
Sure. Thanks. I understood. That's a nice catch. It was stupid of me to not code like that upfront.
Will change the code in a few days once I am free.

**Comment by bhaskatripathi** [comment]
@pohm-github - Updated the load_recommender method. The modified method generates embeddings based on PDF file name and page number and checks if the embeddings file exists before loading or generating it.
