### ISSUE TITLE
Extract Key Information from Invoice PDF's

### ISSUE THREAD

**Issue by Rishi-NF** [bhaskatripathi/pdfGPT#106]
Would i be able to extract key information from invoice pdf files and produce them into a JSON format?

**Comment by bhaskatripathi** [comment]
Yes of course you can try it in the demo link

**Comment by Rishi-NF** [comment]
I tried but i got a found nothing answer, it will give me information if i ask one by one, i attached pictures for more context. 

**When i prompt like this it gives a "found nothing" answer.**
<img width="613" alt="Screenshot 2023-09-28 at 14 36 31" src="https://github.com/bhaskatripathi/pdfGPT/assets/124362385/f07f4942-bc28-4823-8e39-74a36ed5dd17">

**When i ask like this it works:**
<img width="583" alt="Screenshot 2023-09-28 at 14 37 56" src="https://github.com/bhaskatripathi/pdfGPT/assets/124362385/6d9d8447-1f77-4f36-b09d-6deb95347967">

**Comment by bhaskatripathi** [comment]
Yes, it Ned's to be customized as per your requirement
