### ISSUE TITLE
Type of supported data in PDF

### ISSUE THREAD

**Issue by Dipankar1997161** [bhaskatripathi/pdfGPT#107]
Hello @bhaskatripathi,

Have you tested how your system parse **PDF with Tables**. 
For example, research paper have text and tables at certain times. This is important for me to work with. 

I will wait for your response.

**Comment by bhaskatripathi** [comment]
Yes I have tested it with gpt3.5 and 4. But it gives better results of you ask to refer the results by stating the table number

**Comment by Dipankar1997161** [comment]
sounds great. did you set any prompts for providing the table number?  or just ask.. 

From table number 2, what is this value of bla bla. 

Isn't that a bit weird for the user to always state table numbers?

**Comment by Dipankar1997161** [comment]
> Yes I have tested it with gpt3.5 and 4. But it gives better results of you ask to refer the results by stating the table number

Hello, I tested the table QnA. There are discrepancies in the response. I believe this could be due to the table extraction from PDF not being successfully accurate. 

https://arxiv.org/pdf/2201.04127.pdf

I tried the following pdf and the error is mostly in Table 1 for subject 387 and some random ones too.

**Comment by bhaskatripathi** [comment]
May be you can try using text-davinci-003 for even better results
