### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by oscarjose9423** [bhaskatripathi/pdfGPT#108]
Is the demo down or something? This tool has been really helpful lately in asking questions about youtube videos (I extracted the transcript) thanks!

**Comment by bhaskatripathi** [comment]
It works: https://huggingface.co/spaces/bhaskartripathi/pdfGPT_Turbo

**Comment by dzanaga** [comment]
It's not working for me. I tried the demo and as well as the local deployment, but I can't get to chat...

In the demo do you get anything if you ask it to summarize this pdf?https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

After submitting, I see the 3 dots and then nothing.

In local deployment I get:
```
API Error: Bad gateway. {"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}} 502 {'error': {'code': 502, 'message': 'Bad gateway.', 'param': None, 'type': 'cf_bad_gateway'}} {'Date': 'Wed, 08 Nov 2023 14:32:08 GMT', 'Content-Type': 'application/json', 'Content-Length': '84', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Server': 'cloudflare', 'CF-RAY': '822e86016c5e2e20-BRU', 'alt-svc': 'h3=":443"; ma=86400'}
```

**Comment by nunes-bruno-m** [comment]
How do we know why it doesn't work?
Using https://huggingface.co/spaces/bhaskartripathi/pdfGPT_Turbo, I make the question and it quickly shows the loader and then nothing appears.

**Comment by bhaskatripathi** [comment]
Yes. I had suppressed the exception when openAI returns an error. I will show an explicit message.
