### ISSUE TITLE
create api to use it 

### ISSUE THREAD

**Issue by smeet07** [bhaskatripathi/pdfGPT#15]

**Comment by sabrysm** [comment]
Yeah!

**Comment by Sassun** [comment]
+1

**Comment by deepankarm** [comment]
@smeet07 pdfGPT is now available as APIs - https://github.com/bhaskatripathi/pdfGPT#use-pdfgpt-on-production-using-langchain-serve

**Comment by zanxiaoyu** [comment]
> @smeet07pdfGPT 现在可用作 API - https://github.com/bhaskatripathi/pdfGPT#use-pdfgpt-on-production-using-langchain-serve

no Route matched with those values   and  statusCode: 404

**Comment by deepankarm** [comment]
@zanxiaoyu the endpoint added in the readme was just an example. Please deploy your own app using `lc-serve deploy jcloud api` and replace the url in the curl commands to your app's url.
