### ISSUE TITLE
just errors

### ISSUE THREAD

**Issue by gregcault** [bhaskatripathi/pdfGPT#28]
uploaded a test document, background.pdf, asked it to give feedback, returned an error

**Comment by dezerving** [comment]
> uploaded a test document, background.pdf, asked it to give feedback, returned an error

What was the error?

**Comment by gregcault** [comment]
you dont show error beyond just a red box

**Comment by bhaskatripathi** [comment]
from the logs, it seems your document was empty. Will add a check to handle empty documents
![image](https://user-images.githubusercontent.com/35177508/235290265-a2829fbf-80f6-4f78-acfd-4ca117297b36.png)

**Comment by bhaskatripathi** [comment]
I have added a check to handle empty PDF documents
