### ISSUE TITLE
Request: GPT-3.5-turbo

### ISSUE THREAD

**Issue by 200901002** [bhaskatripathi/pdfGPT#33]
Is there any specific reason (like less hallucianation) why we are using text-davinci-003 over gpt-3.5-turbo? 

It would be nice if there was an option to switch to Gpt-3.5 turbo.

**Comment by bhaskatripathi** [comment]
text-DaVinci-003 is superior in this usecase because fine tuning with gpt-3.5-turbo has more guardrails. You'd more often see "As an AI language model, I do not..." kind of messages.
