### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by KHDOUDI** [bhaskatripathi/pdfGPT#34]
Hello,
Great work, only want to try.

am i the only one that cannot run the demo ? it load the pdf, i past the key then ask the question.

The result is "Error" even i tried on several PDF files.

Any suggestion ?

Thank you

**Comment by 200901002** [comment]
It is working for me.

1. Check if your API key is correct.
2. Your Pdf should contain text (not image based pdf)
3. You should pass either **URL** of pdf or **file** not both
4.  If you question is too short it will not work.

**Comment by KHDOUDI** [comment]
Thank you for your feedback, it seems that my credit of OPENAI account has expired.

**Comment by KHDOUDI** [comment]
Solved by trying new account credits.
