### ISSUE TITLE
Add ChatMemory to pdfGPT

### ISSUE THREAD

**Issue by Sassun** [bhaskatripathi/pdfGPT#39]
I would be super valuable to be able to have a chat memory / history for pdfGPT

See here a langchain example:
https://python.langchain.com/en/latest/modules/chains/index_examples/chat_vector_db.html

**Comment by bhaskatripathi** [comment]
planned in backlog for V2

**Comment by Sassun** [comment]
Awesome, any rough timeline on this?

**Comment by bhaskatripathi** [comment]
you can expect that by end of month as I am short of bandwidth as of now.

**Comment by bhaskatripathi** [comment]
Implemented chat history : https://huggingface.co/spaces/bhaskartripathi/pdfGPT_Turbo
