### ISSUE TITLE
It isn't working ... the seconds timer keeps going.

### ISSUE THREAD

**Issue by nynewco** [bhaskatripathi/pdfGPT#4]
Am I missing something? How long should one wait for a response?

**Comment by Icybannie** [comment]
Facing the same issues, thought i was crazie

**Comment by bhaskatripathi** [comment]
It uses universal sentence encoder call from higgingface. Sometimes hugging face infra goes bersek. Quick fix is to copy that model and host on an alternate infra.

**Comment by Icybannie** [comment]
How do i do that

**Comment by Icybannie** [comment]
hilo
?

**Comment by bhaskatripathi** [comment]
If you are running on your local

> Am I missing something? How long should one wait for a response?

**Comment by bhaskatripathi** [comment]
https://dataintegration.info/serve-a-tensorflow-hub-model-in-google-cloud-with-vertex-ai

**Comment by bhaskatripathi** [comment]
The wait time also depends upon the network performance.
Closing the issue as it is working fine on : https://bhaskartripathi-pdfchatter.hf.space with a minimal wait time.
