### ISSUE TITLE
 Text Not Found in PDF.

### ISSUE THREAD

**Issue by sam19872014** [bhaskatripathi/pdfGPT#40]
Hello,

I tested many pdf in the demo but i keep getting this error

![image](https://user-images.githubusercontent.com/132385458/235732131-1b539bf7-2d29-454b-ac94-74659607fc5d.png)

**Comment by sam19872014** [comment]
here is the link of a research paper for the debuging: https://pureadmin.uhi.ac.uk/ws/files/15417485/Sanmark2004_OPIA34.pdf

**Comment by bhaskatripathi** [comment]
Also, please delete your API key (in the screenshot) as it is your secret key as someone may misuse it.

**Comment by sam19872014** [comment]
Thanks a lot for ur amazing work. Several questions:

1) when will the v2 film be available?
2) what is the max pages supported for this current version?
3) is it possible to give in the entry a .txt file or .Doc in the future?

**Comment by bhaskatripathi** [comment]
1. V2 will be available by this month end as I am already on a full time job and manage time only on weekends.
2. Max pages I have tested was around 30-35. However, once the vectorDB support is given, there should be no limit theoretically.
3. I will add support for multiple formats including txt, docx, HTML etc. in V2.

**Comment by 200901002** [comment]
hmm is 30 pages limit for hugging face alone? because I have tested with **1902 pages of .pdf** it worked for me. but I ran it locally on my own PC.

**Comment by bhaskatripathi** [comment]
wow ! that is great. Hugging face infra is little slow and has its own limitations. 
would you mind sharing the instructions for local installation? I can add them to the readme.md or you can be a contributor by submitting a PR.

**Comment by 200901002** [comment]
Sure here are the steps I followed.  @bhaskatripathi 


1. Pull the image by entering the following command in your terminal or command prompt:

    `docker pull registry.hf.space/bhaskartripathi-pdfchatter:latest`

2. Download the Universal Sentence Encoder locally to your project's root folder. This is important because otherwise, 915 MB will be downloaded at runtime, and it may cause your app to feel stuck.

   - Download the encoder using this link: https://tfhub.dev/google/universal-sentence-encoder/4?tf-hub-format=compressed
   - Extract the downloaded file and place it in your project's root folder as shown below:

    ```
    Root folder of your project
    └───Universal Sentence Encoder
    |   ├───assets
    |   └───variables
    |   └───saved_model.pb
    |
    └───app.py
    ```

   - If you have downloaded it locally, replace the code on line 68 in the API file:

     ```
     self.use = hub.load('https://tfhub.dev/google/universal-sentence-encoder/4')
     ```

     with:

     ```
     self.use = hub.load('./Universal Sentence Encoder')
     ```

3. Now, To run PDF-GPT, enter the following command:

    `docker run -it -p 7860:7860 --platform=linux/amd64 registry.hf.space/bhaskartripathi-pdfchatter:latest python app.py`

I hope this helps you get started with running PDF-GPT locally!

**Comment by 200901002** [comment]
For the record I want to show it's working with 1900 pages long .pdf

![image](https://user-images.githubusercontent.com/112180722/235913523-c7ee5d10-9ee2-4d57-b8b3-3bb9fff67be7.png)

**Comment by bhaskatripathi** [comment]
@200901002 Adhithya  Excellent! This is super helpful, man. I will update the readme file and add your name to the credits.

**Comment by sam19872014** [comment]
I had uploaded a pdf 2 pages on your demo link and it is working but  having an error when trying read the same pdf when deploying it localy. what do you think the issue is coming from?

![image](https://user-images.githubusercontent.com/132385458/235940084-9bedb3f7-ff90-4752-baa5-7497d4efdad8.png)

![image](https://user-images.githubusercontent.com/132385458/235940148-5cef3a9e-8794-4ef2-8f14-cad7e1f4fd45.png)

![image](https://user-images.githubusercontent.com/132385458/235940257-925b73fd-f909-4db1-8f15-1c37921aa451.png)

**Comment by bhaskatripathi** [comment]
@sam19872014 
![image](https://user-images.githubusercontent.com/35177508/235953184-5bc51796-4467-42b8-b755-be74fcc49630.png)

**Comment by sam19872014** [comment]
What I mean is that I run your code locally on my computer and i get the errors in the screenshot. I can find how to solve it in order to be able to run ur project locally on my computer

**Comment by newdispatcher** [comment]
When i am trying to run docker image following error is showing and app is not opening on port 7860

root@ubuntu:/home/ubuntu/pdfGPT# docker run -it -p 7860:7860 --platform=linux/amd64 registry.hf.space/bhaskartripathi-pdfchatter:latest python app.py
2023-05-04 08:51:09.625207: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-04 08:51:09.625301: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Does GPU require for this code to run

**Comment by 200901002** [comment]
You can safely ignore that warning. It can indeed run on CPU alone.
