### ISSUE TITLE
cant lc serve 

### ISSUE THREAD

**Issue by bllfoad** [bhaskatripathi/pdfGPT#42]
'lc-serve' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bhaskatripathi** [comment]
@deepankarm - FYI

**Comment by bllfoad** [comment]
![image](https://user-images.githubusercontent.com/100096228/236009091-857264f8-eb38-4854-abdc-31d9c252dd1c.png)
i didn't understand i keep getting this error even when `pip install langchain-serve`

**Comment by bllfoad** [comment]
thanks

**Comment by bllfoad** [comment]
![image](https://user-images.githubusercontent.com/100096228/236025377-c67863d6-da8d-4689-96dd-7e3d3b56705e.png)
I tried giving the full path and it worked put what is the problem now its still loading and when using http://localhost:8080 it gives error 
also, this command helped me install the requirements successfully 
`New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" ` -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`
