### ISSUE TITLE
Waiting gateway...

### ISSUE THREAD

**Issue by sam19872014** [bhaskatripathi/pdfGPT#43]
![image](https://user-images.githubusercontent.com/132385458/236041870-c69b9ec3-87ff-4a37-a09e-30122e4e798d.png)

As u can see the server nerver deploy. What can be the issue? I installed all requirements needed in the requirements.txt

**Comment by deepankarm** [comment]
Hey @sam19872014, can you please pull the latest main and retry? PR #46 should fix this.

**Comment by sam19872014** [comment]
it is now working but cant get an answer from a 2 page pdf 
![image](https://user-images.githubusercontent.com/132385458/236238362-9f1f39be-07bb-4f88-a06a-c7cad2329282.png)
