### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by oktaborg** [bhaskatripathi/pdfGPT#47]
I would like to run this in docker for unraid. Is this something you can try?

**Comment by 200901002** [comment]
There will be a official guide soon from the Creator himself. but for now here you go https://github.com/bhaskatripathi/pdfGPT/issues/40#issuecomment-1532917099

**Comment by bhaskatripathi** [comment]
Thanks @200901002 . I have updated the markup.
The instructions are available at:
https://github.com/bhaskatripathi/pdfGPT/blob/main/README.md

**Comment by oktaborg** [comment]
Thanks. I prefer a YouTube guide or a official docker. I have a own setup in my server but in different containers.
