### ISSUE TITLE
server disconnected error

### ISSUE THREAD

**Issue by smeet07** [bhaskatripathi/pdfGPT#52]
I am getting server disonnected error while running the command  lc-serve deploy jcloud api
![image](https://user-images.githubusercontent.com/81572407/236544425-58cee2bd-4e2b-4de0-826d-38500a34fcc8.png)

**Comment by deepankarm** [comment]
@smeet07 Is this a consistent error, or does a retry help?

**Comment by smeet07** [comment]
I tried 3-4 times every time it creates a cloud which is successfully created and then it starts deploying, after a while it shows sever disconnected error

**Comment by deepankarm** [comment]
Hi @smeet07, do you mind joining our [slack](https://jina.ai/slack/) to have an easier discussion?

**Comment by smeet07** [comment]
Also is it possible to make a post request without hosting it on jina?

**Comment by smeet07** [comment]
> Hi @smeet07, do you mind joining our [slack](https://jina.ai/slack/) to have an easier discussion?

cool

**Comment by smeet07** [comment]
cool
