### ISSUE TITLE
Got error when using Chinese

### ISSUE THREAD

**Issue by frank0828** [bhaskatripathi/pdfGPT#53]
I really like your app, however, I uploaded a pdf that is in Chinese, and I also asked a question in Chinese, but when I run the result, I got an error. 
When will it support Chinese pdf? Really looking forward to it.

**Comment by bhaskatripathi** [comment]
I will start looking for Multi-lingual support including Chinese at top priority in about a month's time when I get free. In the mean time, I would request other contributors to look into this issue.

**Comment by bhaskatripathi** [comment]
Not able to add support for Chinese language as of now.
