### ISSUE TITLE
Key Error:'name'

### ISSUE THREAD

**Issue by sukjinlee** [bhaskatripathi/pdfGPT#6]
![image](https://user-images.githubusercontent.com/44647107/231354906-27df4c52-b0b2-4b5f-956c-c2b3c28aa62b.png)

What does this error code mean?
Is it because I'm using the wrong API?
If yes, which api key should I use?

**Comment by bhaskatripathi** [comment]
can you please share the complete trace? It is unclear if it is due to wrong API as I am not able to see any API related error. I would suggest you to try running on huggingface and see if you get the same error there as well.

**Comment by bhaskatripathi** [comment]
Your API Key has expired.
