### ISSUE TITLE
so where is the index data?

### ISSUE THREAD

**Issue by ozbillwang** [bhaskatripathi/pdfGPT#61]
When preparing questions and answers, we typically follow these steps:

1. Extract text from various data sources, such as websites, PDFs, CSVs, or plain text files. The extracted text can be saved in different locations.
2. Create embeddings, which produce an index file as output.
3. Answer questions by referencing the index created in the previous step.

However, when I run the API and App locally for this project, I cannot see the data generated in steps (1) and (2). I am curious about where the data is stored and how it works.

**Comment by shusiner** [comment]
The data is just stored in memory. Every time when you refresh the app, there is no saved data and you need to upload the document again. you could store the data and output to .txt if you want by adding a line to output the data

Refer to the code here:

Turning pdf to text:
https://github.com/bhaskatripathi/pdfGPT/blob/649afc6a2418825aea53bfd59c14e73e6db572e4/api.py#L106

Turn text into embedding:
https://github.com/bhaskatripathi/pdfGPT/blob/649afc6a2418825aea53bfd59c14e73e6db572e4/api.py#L76
