### ISSUE TITLE
i upload a pdf to the demo, but it can not work,  any body success make the demo work ??

### ISSUE THREAD

**Issue by sky-L** [bhaskatripathi/pdfGPT#67]

**Comment by bhaskatripathi** [comment]
please share the screenshot of the error that you are getting?

**Comment by Ekuboh** [comment]
![image](https://github.com/bhaskatripathi/pdfGPT/assets/125041817/36267290-755f-49dd-ac1e-8922c8278f20)
hello, Why did it take 20,000 seconds?

**Comment by bhaskatripathi** [comment]
please check now. Huggingface had updated its radio API so the demo wasn't working. I have set it back.

**Comment by renren0180** [comment]
![Screenshot_2023-05-28-00-19-18-50](https://github.com/bhaskatripathi/pdfGPT/assets/94297877/318856ae-572f-41e3-8c97-b1e1f23eb02d)
I encounter too

**Comment by bhaskatripathi** [comment]
@renren0180 It seems to be working. Please check your key if it is expired because I can see in logs some exchausted keys are used.
![image](https://github.com/bhaskatripathi/pdfGPT/assets/35177508/652dc2cb-c1e6-489e-9d5b-2e5b6ff3248a)
