### ISSUE TITLE
universal-sentence-encoder suitable for only English or multi languages?

### ISSUE THREAD

**Issue by 1991Troy** [bhaskatripathi/pdfGPT#68]
the most significant point for this work is using universal-sentence-encoder instead of openai embedding.
I use it for english embedding, it seems good according to the KNN result based on the embedding .
I use it for other language embedding, it seems not good.

**Comment by bhaskatripathi** [comment]
You are right. This work's main novelty is to improve the embeddings by using Universal Sentence Encoder and marrying it with KNN to get the best top-K results. Universal Sentence Encoder has not been tested extensively with languages other than English. So you are right, more needs to be explored. This code was written somewhere around Jan 2023 when all this interaction with PDF files were relatively new. Now, there are many advanced libraries to do this work but I am not sure why everyone is so obsessed with OpenAI embeddings. I have tested them in various scenarios and it gives poor results. I will upgrade or create a new STOA for multiple-languages document embeddings when I get time.
Right now caught with other things in life.
