### ISSUE TITLE
text-DaVinci-003 vs gpt-4

### ISSUE THREAD

**Issue by ollieanwyll** [bhaskatripathi/pdfGPT#69]
Hey, awesome project.

just curious about the use of text-DaVinci-003 over gpt-4. 
would you still recommend using text-DaVinci-003 over gpt-4 if it’s available to the user?
If so, would you be so kind as to explain why text-DaVinci-003 is a better choice?
Thanks

**Comment by bhaskatripathi** [comment]
Hey @ollieanwyll ,
This was developed in Feb,23 when GPT4 wasn't launched. For some reason, I am still in the waitinglist of GPT4 API so I could not test the GPT4 model and compare its results to text-DaVinci-003. However,  I am sure that GPT4 will give improved output and has longer context of 32K tokens compared to the 4096 tokens on text-DaVinci-003. Some contributor can submit a PR for this change.

**Comment by Yiiipu** [comment]
I tried 3.5 and 4, they work great. They feel more alive when giving responses. 3.5 is also faster and cheaper. I also manage to give them conversation memory by using 3.5 or 4. You can check out my repo: https://github.com/Yiiipu/SimplePDF

**Comment by bhaskatripathi** [comment]
@Yiiipu - This is great!
Also, I have added support for all Turbo models now including GPT4:
https://huggingface.co/spaces/bhaskartripathi/pdfGPT_Turbo
