### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by AnzeKop** [bhaskatripathi/pdfGPT#76]
The Online demo isn't working, just throws up an error, is it possible one of the API calls not working?

**Comment by bhaskatripathi** [comment]
It is working for me but I can see in the logs that remote connection was disconnected which happens if there is an updated in huggingface spaces infrastructure. 
you can first trying running this :
enter your key and, pdf URL : https://arxiv.org/pdf/1706.03762.pdf 
question  : summarize the paper
 If it works and your pdf is not working then I can look into the issue.

![image](https://github.com/bhaskatripathi/pdfGPT/assets/35177508/97f1e49e-af01-4867-9bf4-0f17e963b839)

**Comment by hrushik98** [comment]
I just checked now and it's working fine.

**Comment by ddlsundae** [comment]
I don't know if it's just me or what but it gives me error everytime i ask it something 
I'm uploading the archive and asking but it charges like 1 o 2 seconds and throw me "Error".

**Comment by AnzeKop** [comment]
> It is working for me but I can see in the logs that remote connection was disconnected which happens if there is an updated in huggingface spaces infrastructure. you can first trying running this : enter your key and, pdf URL : https://arxiv.org/pdf/1706.03762.pdf question : summarize the paper If it works and your pdf is not working then I can look into the issue.
> 
> ![image](https://user-images.githubusercontent.com/35177508/242713810-97f1e49e-af01-4867-9bf4-0f17e963b839.png)

I've tested it with your PDF and its still throwing the same error and mentioned above. loads for 1 or 2 seconds and then says error.

Also is there a way to maybe put some from scratch tutorial on how to localy install (not really the best at the backend)

**Comment by ddlsundae** [comment]
Hello Anze! If you want to run it locally, you can ask ChatGPT how to do it. I did it using PowerShell, for example. I downloaded Docker and a few other things that are required, but I was able to run it locally. It's the same thing as using the demo. What is probably happening to you is that you have reached the usage limit or have already exceeded the monthly usage allocation. What I did to fix this was adding a payment method, as someone on the OpenAI forum recommended (a tragic mistake for me, haha). It's nothing, I mean, it's $5 USD. Unfortunately, I'm from Argentina, and with taxes, the $5 becomes $10 USD, and that is a lot - sadly - for me at least.

I will copy and paste the message from OpenAI support:

"We are now placing a $5.00 temporary authorization hold on credit cards used to set up the pay-as-you-go plan for API accounts. This is part of our preventive measures, but it is not an actual charge. This pending transaction or temporary hold usually disappears after a few days. At the end of each calendar month, you will only be charged for your usage during that month."

Hope this helps you, sorry for my bad eng/grammar. Take care!

**Comment by AnzeKop** [comment]
Thats not possible as is this is the first time i've had to generate an openAI key for anything unless the 5$ is standard before even starting

**Comment by ddlsundae** [comment]
Have you not used ChatGPT since its release? It could be due to two reasons: either you just started your account or it has been a month since you started asking questions to ChatGPT, or you have asked many questions.

**Comment by CRELYTICA-OliverSayers** [comment]
I have had issues with running it locally. @ddlsundae do you have an Nvidia graphics card? Running TensorRT is not possible on Intel graphics cards. My computer only has an Intel graphics card. I believe this is why it is not working for me locally.

**Comment by AnzeKop** [comment]
Aha yeah it was API Keys fault, wierd showed I had budget left. Made new account and tested it with that API key and it worked
