### ISSUE TITLE
Does not support Chinese pdf?

### ISSUE THREAD

**Issue by jerrychen1989** [bhaskatripathi/pdfGPT#80]
Chinese pdf upload question reported error, do not support Chinese pdf?

**Comment by newbiethetest** [comment]
I cannot upload Chinese either. Whenever I try to upload, there is an error message.

**Comment by bhaskatripathi** [comment]
Sorry, it would not be possible to provide support in Chinese language as I do not understand mandrian right now, therefore not able to code specific support to reduce token request size. More than a programming problem, it seems like a language specific demand to change the code which I am not able to do right now.
