### ISSUE TITLE
Feature request: Remember conversation history

### ISSUE THREAD

**Issue by imacfan** [bhaskatripathi/pdfGPT#87]
Remember conversation history so that it bot can refer to previous quesiton and answer as context

**Comment by MTrevoux** [comment]
Hi,

There is a big technical problem here.

Your request will grow the 2*n rate as the API can't remember anything.
It will be required to keep the context within each API call and you will quickly reach your key limit.

Imagine:
    First question: you have a context of 1000 token
    Second question: 1000 token + X1 token from the answer
    Third question: 1000 + X1 + X2
    Fourth question: 1000 + X1 + X2 + X3

Within 4 questions you have reached more than 4000 tokens. As long as the API works that way, the benefits will be minimum.

**Comment by Yiiipu** [comment]
Hey, I fixed the problem (it has memory, but also remains token efficient) and made a version that runs locally on your computer so you do not need to upload anything to a website. However it is only available on Mac.
Check my repo: https://github.com/Yiiipu/SimplePDF

**Comment by bhaskatripathi** [comment]
ChatHistory feature has been implemented. Demo here: https://huggingface.co/spaces/bhaskartripathi/pdfGPT_Turbo
