### ISSUE TITLE
"The only open source solution to turn your pdf files in a chatbot!"

### ISSUE THREAD

**Issue by psociety** [bhaskatripathi/pdfGPT#88]
Why are you lying? There are older and bigger open source projects that do the same:
https://github.com/arc53/DocsGPT
https://github.com/mayooear/gpt4-pdf-chatbot-langchain

**Comment by bhaskatripathi** [comment]
@psociety Constructive criticism is welcome but it makes me laugh to see such a juvenile comment. Keep the discourse professional. Back when this library was penned, the solutions referenced in the readme file were all proprietary.
