### ISSUE TITLE
more errors

### ISSUE THREAD

**Issue by xaccell** [bhaskatripathi/pdfGPT#9]
It works for a while then:

AttributeError: 'SemanticSearch' object has no attribute 'nn'

**Comment by bhaskatripathi** [comment]
I am able to see error free responses on https://huggingface.co/spaces/bhaskartripathi/pdfChatter
![image](https://user-images.githubusercontent.com/35177508/232323903-da9a027a-151b-4479-b9db-a0f26b8532d5.png)

please describe the error in more detail.

**Comment by bhaskatripathi** [comment]
I am able to see error free responses on : https://huggingface.co/spaces/bhaskartripathi/pdfChatter
please describe the scenario when you get it.
![image](https://user-images.githubusercontent.com/35177508/232323966-fb7300c9-0f76-42ee-a648-dd617cec99da.png)
